plugins:
  - babel
env:
  es6: true
  node: true
  mocha: true
parser: babel-eslint
extends:
  - 'airbnb-base'
rules:
  no-console: off
  class-methods-use-this: off
  import/no-extraneous-dependencies: ["error", {"devDependencies": ['./src/tests/**']}]
  no-underscore-dangle: ["error", { "allow": ["_id"] }]
  prefer-destructuring: off
  no-unused-vars: ["error", { "varsIgnorePattern": "should|expect" }]
  arrow-parens: ["error", "always"]
  global-require: off
  arrow-body-style: off
  consistent-return: off
  newline-per-chained-call: off
  quotes: ["error", "single", { "allowTemplateLiterals": true }]
  no-param-reassign: ["error", { "props": false }]
overrides:
  - files: ["src/tests/*.js"]
    rules:
      no-unused-expressions: "off"
